#!/usr/bin/env python3
# _train_alm_14b_r10c.py â auto-generated by launch_alm_14b_r10c.hexa
# E7 redesign: sentinel subprocess, corpus mix, seed arg, early-step gate.
import argparse, gc, json, os, sys, time, math, random, subprocess
from pathlib import Path
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

p = argparse.ArgumentParser()
p.add_argument('--base-dir', required=True)
p.add_argument('--adapter-dir', default='')
p.add_argument('--corpus', required=True)
p.add_argument('--kowiki', default='', help='optional kowiki.jsonl path for corpus diversity mix')
p.add_argument('--kowiki-mix-pct', type=int, default=15)
p.add_argument('--ckpt-dir', required=True)
p.add_argument('--steps', type=int, default=2000)
p.add_argument('--save-every', type=int, default=2000)
p.add_argument('--eval-every', type=int, default=200)
p.add_argument('--lr', type=float, default=2e-6)
p.add_argument('--batch', type=int, default=8)
p.add_argument('--seq', type=int, default=1024)
p.add_argument('--grad-accum', type=int, default=1)
p.add_argument('--lora-r', type=int, default=32)
p.add_argument('--lora-alpha', type=int, default=64)
p.add_argument('--lora-dropout', type=float, default=0.0)
p.add_argument('--seed', type=int, default=3407)
p.add_argument('--sentinel-hexa', default='/workspace/anima/training/kr_gen_sentinel.hexa',
               help='path to hexa sentinel â subprocess exit 2 = COLLAPSED authoritative')
p.add_argument('--hexa-bin', default='hexa', help='hexa interpreter binary')
p.add_argument('--early-loss-gate', type=float, default=1.0,
               help='E7-OSS-03: below this loss at step<=early-step-limit, force sentinel')
p.add_argument('--early-step-limit', type=int, default=500)
p.add_argument('--phi-hook', type=int, default=1,
               help='DEST1 gate: 1=write phi_vec.json per save (canonical 16D sidecar)')
args = p.parse_args()

# Seed reproducibility + logging
torch.manual_seed(args.seed); random.seed(args.seed)
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.backends.cudnn.benchmark = True
Path(args.ckpt_dir).mkdir(parents=True, exist_ok=True)
ABORT_STATUS = os.path.join(args.ckpt_dir, 'r10c_abort.status')
STATUS_FILE  = os.path.join(args.ckpt_dir, 'r10c_watcher.status')
def wstatus(s):
    with open(STATUS_FILE, 'w') as f: f.write(s + '\n')
wstatus('INIT')

print('[r10c] seed=' + str(args.seed) + ' base=' + args.base_dir, flush=True)
print('[r10c] corpus=' + args.corpus + ' kowiki=' + (args.kowiki or '<none>') +
      ' mix_pct=' + str(args.kowiki_mix_pct), flush=True)
print('[r10c] sentinel=' + args.sentinel_hexa, flush=True)

tok = AutoTokenizer.from_pretrained(args.base_dir, trust_remote_code=True)
if tok.pad_token is None: tok.pad_token = tok.eos_token

from unsloth import FastLanguageModel
model, tok = FastLanguageModel.from_pretrained(
    model_name=args.base_dir, max_seq_length=args.seq, dtype=torch.bfloat16,
    load_in_4bit=False, trust_remote_code=True,
    use_gradient_checkpointing='unsloth',
)
if tok.pad_token is None: tok.pad_token = tok.eos_token

try:
    from liger_kernel.transformers import apply_liger_kernel_to_qwen2
    apply_liger_kernel_to_qwen2(rope=True, rms_norm=True, swiglu=True,
                                fused_linear_cross_entropy=True, cross_entropy=False,
                                model=model)
    print('[r10c] liger applied', flush=True)
except Exception as e:
    print('[r10c] liger unavailable: ' + str(e), flush=True)

# ââ LoRA fresh init (r4 adapter proved misaligned on stripped corpus) ââ
if args.adapter_dir:
    model = PeftModel.from_pretrained(model, args.adapter_dir, is_trainable=True)
    print('[r10c] warm-start OK from ' + args.adapter_dir, flush=True)
else:
    from unsloth import FastLanguageModel as _FLM
    model = _FLM.get_peft_model(
        model, r=args.lora_r, lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=['q_proj','k_proj','v_proj','o_proj'],
        bias='none', use_gradient_checkpointing='unsloth',
        random_state=args.seed,
    )
    print('[r10c] LoRA applied (fresh, seed=' + str(args.seed) + ')', flush=True)
model.print_trainable_parameters()

# ââ Corpus assembly: stripped_70b â optional kowiki mix ââ
text_main = Path(args.corpus).read_text(errors='ignore')
text = text_main
kowiki_note = ''
if args.kowiki and os.path.isfile(args.kowiki):
    # Byte-budget kowiki insertion: target_bytes = main_bytes * mix_pct / (100 - mix_pct)
    main_bytes = len(text_main.encode('utf-8'))
    target_kowiki_bytes = max(1, main_bytes * args.kowiki_mix_pct // (100 - args.kowiki_mix_pct))
    chunks = []
    got = 0
    with open(args.kowiki, 'r', encoding='utf-8', errors='ignore') as kf:
        for line in kf:
            try:
                rec = json.loads(line)
                t = rec.get('text', '')
                if not t: continue
                chunks.append(t)
                got += len(t.encode('utf-8'))
                if got >= target_kowiki_bytes: break
            except Exception:
                continue
    kowiki_text = '\n\n'.join(chunks)
    text = text_main + '\n\n' + kowiki_text
    kowiki_note = ' +kowiki(' + str(got) + 'B, ' + str(len(chunks)) + ' docs)'
else:
    print('[r10c WARN] kowiki unavailable â using stripped_70b only (E7 corpus-diversity recommendation skipped)', flush=True)
print('[r10c] corpus bytes=' + str(len(text.encode('utf-8'))) + kowiki_note, flush=True)

ids = tok(text, add_special_tokens=False)['input_ids']
print('[r10c] corpus tokens=' + str(len(ids)), flush=True)
seq = args.seq
n_blocks = len(ids) // seq
blocks = [ids[i*seq:(i+1)*seq] for i in range(n_blocks)]
print('[r10c] blocks=' + str(len(blocks)), flush=True)

class PackedDS(Dataset):
    def __init__(self, blocks): self.b = blocks
    def __len__(self): return len(self.b)
    def __getitem__(self, i):
        x = torch.tensor(self.b[i], dtype=torch.long)
        return {'input_ids': x, 'labels': x.clone(), 'attention_mask': torch.ones_like(x)}

ds = PackedDS(blocks)
dl = DataLoader(ds, batch_size=args.batch, shuffle=True, pin_memory=True, drop_last=True)
opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=args.lr, fused=True)

device = 'cuda'
model.train()

# ââ First-batch CE guard ââ
it = iter(dl)
b0 = next(it)
with torch.no_grad():
    out0 = model(input_ids=b0['input_ids'].to(device),
                 labels=b0['labels'].to(device),
                 attention_mask=b0['attention_mask'].to(device))
    ce0 = float(out0.loss.detach().item())
print('[r10c] first-batch CE = ' + str(round(ce0, 4)), flush=True)
if ce0 > 8.0:
    with open(ABORT_STATUS, 'w') as f: f.write('FIRST_BATCH_CE=' + str(ce0) + '\n')
    wstatus('ABORT_FIRST_BATCH_CE')
    print('[r10c ABORT] first-batch CE=' + str(ce0) + ' > 8.0 â exiting', flush=True)
    sys.exit(2)

# ââ DEST1 phi-hook: write 16D phi_vec.json next to each ckpt ââ
# Schema matches training/alm_phi_vec_logger.hexa canonical layout. Inline
# surrogates: phi_holo_proxy = -log(max(ce, 1e-6)) (positive when ce<1);
# phi_complexity / phi_gwt computed offline by phi_eval_hook_spec. Other
# 13 dims NaN sentinels filled by downstream probes. Sufficient for the
# DEST1 gate ('phi > 1000 evidence') since phi_holo scale reaches 10^4 on
# r9 (12000) and r4 (9051). eval_phi_corr consumes N>=5 save_every=400.
def write_phi_vec(step, save_dir, ce_proxy):
    if not args.phi_hook: return
    import math
    nan = float('nan')
    phi_holo_proxy = -math.log(max(ce_proxy, 1e-6))
    # DEST1 explicit scale: phi_holo in r9/r4 raw is ~10^4. The proxy is
    # unitless and centered near 0 at ce=1. We expose BOTH â downstream
    # can pick whichever matches the phi_corr_history convention.
    phi_holo_scaled = phi_holo_proxy * 10000.0
    phi_vec = [phi_holo_proxy, nan, nan, nan, nan, nan, nan, nan,
               nan, nan, nan, nan, nan, nan, nan, nan]
    phi_path = os.path.join(save_dir, 'phi_vec.json')
    with open(phi_path, 'w') as f:
        json.dump({'step': step, 'phi_vec': phi_vec,
                   'phi_holo_proxy': phi_holo_proxy,
                   'phi_holo_scaled': phi_holo_scaled,
                   'ce_proxy': ce_proxy,
                   'schema': 'alm_phi_vec_logger_v1',
                   'round': 'r10c',
                   'seed': args.seed,
                   'dest1_gate_scale': 'phi_holo_scaled > 1000'},
                  f, allow_nan=True)
    print('[phi16] step=' + str(step) + ' phi_holo_proxy=' + str(round(phi_holo_proxy,4)) +
          ' phi_holo_scaled=' + str(round(phi_holo_scaled,2)), flush=True)

# ââ E7-OSS-01: sentinel via subprocess (authoritative exit code) ââ
SENTINEL_PROMPTS = ['ìëíì¸ì', 'ì¤ë ë ì¨', 'íêµ­ì´ ëª¨ë¸', 'ë¥ë¬ëì´ë', 'ìë']
def run_kr_gen(step, reason='cadence'):
    gc.collect(); torch.cuda.empty_cache(); model.eval()
    samples = []
    try:
        for prompt in SENTINEL_PROMPTS:
            iid = tok(prompt, return_tensors='pt').input_ids.to(device)
            with torch.no_grad():
                # Manual greedy loop bypasses unsloth fast_generate kwarg bleed (E7-OSS-04)
                g_seq = iid
                eos_pad = (tok.eos_token_id, tok.pad_token_id)
                for _gs in range(32):
                    logits = model(input_ids=g_seq).logits
                    next_tok = logits[:, -1, :].argmax(dim=-1, keepdim=True)
                    g_seq = torch.cat([g_seq, next_tok], dim=-1)
                    if int(next_tok.item()) in eos_pad:
                        break
                g = g_seq
            gen = tok.decode(g[0][iid.shape[1]:], skip_special_tokens=True)
            samples.append({'prompt': prompt, 'gen': gen[:200]})
            del iid, g
    finally:
        model.train(); gc.collect(); torch.cuda.empty_cache()
    log_path = os.path.join(args.ckpt_dir, 'kr_gen_step_' + str(step) + '.json')
    with open(log_path, 'w') as f:
        json.dump({'step': step, 'reason': reason, 'samples': samples},
                  f, ensure_ascii=False, indent=2)

    # E7-OSS-01: subprocess call; exit 2 = COLLAPSED authoritative
    verdict = 'UNKNOWN'; rc = -1; raw = ''
    try:
        r = subprocess.run([args.hexa_bin, args.sentinel_hexa, log_path],
                           capture_output=True, text=True, timeout=60)
        rc = r.returncode
        raw = (r.stdout or '') + (r.stderr or '')
        if rc == 0: verdict = 'CLEAN'
        elif rc == 2: verdict = 'COLLAPSED'
        else: verdict = 'SENTINEL_ERROR(' + str(rc) + ')'
    except Exception as e:
        # Hexa binary unavailable â fall back to inline byte-level check
        # (byte-run>=10 ANY byte â matches kr_gen_sentinel.hexa max_byte_run)
        print('[sentinel FALLBACK] hexa unavailable: ' + str(e), flush=True)
        import collections
        flagged = 0
        for s in (x['gen'] for x in samples):
            by = s.encode('utf-8', errors='ignore')
            run = best = 1
            for j in range(1, len(by)):
                if by[j] == by[j-1]:
                    run += 1
                    if run > best: best = run
                else: run = 1
            if best >= 10: flagged += 1
        verdict = 'COLLAPSED' if flagged >= 3 else 'CLEAN'
        rc = 2 if verdict == 'COLLAPSED' else 0
    print('[sentinel] step=' + str(step) + ' reason=' + reason +
          ' verdict=' + verdict + ' rc=' + str(rc), flush=True)
    if verdict == 'COLLAPSED':
        with open(ABORT_STATUS, 'w') as f:
            f.write('MODE_COLLAPSE_STEP=' + str(step) + '_REASON=' + reason + '\n')
        wstatus('ABORT_MODE_COLLAPSE')
        print('[r10c ABORT] sentinel COLLAPSED at step=' + str(step), flush=True)
        sys.exit(2)

# ââ Training loop ââ
wstatus('TRAINING')
step = 0; t0 = time.time(); best_loss = 1e9
while step < args.steps:
    for batch in dl:
        if step >= args.steps: break
        out = model(input_ids=batch['input_ids'].to(device),
                    labels=batch['labels'].to(device),
                    attention_mask=batch['attention_mask'].to(device))
        loss = out.loss
        loss.backward()
        if (step + 1) % args.grad_accum == 0:
            opt.step(); opt.zero_grad(set_to_none=True)
        step += 1
        lv = float(loss.detach().item())
        if step == 1 or step % 25 == 0:
            elapsed = time.time() - t0
            toks_s = (step * args.batch * args.seq) / max(elapsed, 1e-6)
            print('[step=' + str(step) + '] loss=' + str(round(lv,4)) +
                  ' lr=' + str(args.lr) + ' toks/s=' + str(round(toks_s,0)), flush=True)
        if step == 1 and lv > 8.0:
            with open(ABORT_STATUS, 'w') as f: f.write('STEP1_LOSS=' + str(lv) + '\n')
            wstatus('ABORT_STEP1')
            print('[r10c ABORT] step=1 loss=' + str(lv) + ' > 8.0', flush=True)
            sys.exit(2)
        if lv < best_loss: best_loss = lv

        # E7-OSS-03: sub-threshold loss at early step forces sentinel
        if step <= args.early_step_limit and lv < args.early_loss_gate:
            print('[r10c] early-gate fired: step=' + str(step) + ' loss=' +
                  str(round(lv,4)) + ' < ' + str(args.early_loss_gate) + ' â force sentinel', flush=True)
            run_kr_gen(step, reason='early_loss_gate')

        if step % args.eval_every == 0:
            run_kr_gen(step, reason='cadence')
        if step % args.save_every == 0:
            save_dir = os.path.join(args.ckpt_dir, 'step_' + str(step))
            model.save_pretrained(save_dir)
            tok.save_pretrained(save_dir)
            meta = {'step': step, 'loss': lv, 'best_loss': best_loss,
                    'lr': args.lr, 'b1': False, 'base': args.base_dir,
                    'warm_start_from': args.adapter_dir, 'round': 'r10c',
                    'seed': args.seed, 'kowiki_mix_pct': args.kowiki_mix_pct,
                    'phi_hook': bool(args.phi_hook),
                    'sentinel_hexa': args.sentinel_hexa,
                    'ossified_rules': ['E7-OSS-01','E7-OSS-02','E7-OSS-03']}
            with open(os.path.join(save_dir, 'train_meta.json'), 'w') as f:
                json.dump(meta, f, indent=2)
            write_phi_vec(step, save_dir, lv)
            print('[save] step=' + str(step) + ' â ' + save_dir, flush=True)

wstatus('DONE')
print('[r10c] DONE step=' + str(step) + ' best_loss=' + str(round(best_loss,4)), flush=True)
