#!/usr/bin/env bash
# tool/hexa_sim_index_gen.sh — auto-generate design/hexa_sim/INDEX.md from filesystem
#
# usage: bash tool/hexa_sim_index_gen.sh [--out PATH]
#
# Reads design/hexa_sim/* and emits sorted markdown table:
#   | file | type | date | bytes | 1-line desc |
#
# Type heuristic from filename pattern:
#   *omega_cycle*.json  → witness
#   *_review.md         → review
#   *_audit.md          → audit
#   *_decision.md       → decision
#   SECURITY_AUDIT.md   → audit
#   M*_definition.md    → audit
#   SESSION_*.md / NEXT_SESSION_*.md → session
#   README*.md / INDEX*.md / SYNTHESIS*.md → corpus_doc
#   falsifiers.jsonl    → registry
#   falsifier_history*.jsonl → ledger
#   *.py / *.sh         → script
#
# 1-line desc is best-effort: first markdown heading or JSON 'title' field
#
# raw 73 minimal; raw 71 report-only (no mutation); raw 80 stdout-clean

set -uo pipefail

NEXUS_ROOT="${NEXUS_ROOT:-$HOME/core/nexus}"
DIR="$NEXUS_ROOT/design/hexa_sim"
OUT="$DIR/INDEX.md"

while [ $# -gt 0 ]; do
    case "$1" in
        --out) OUT="$2"; shift 2 ;;
        --help|-h) echo "usage: $0 [--out PATH]"; exit 0 ;;
        *) echo "unknown: $1" >&2; exit 1 ;;
    esac
done

[ -d "$DIR" ] || { echo "error: $DIR missing" >&2; exit 1; }

classify() {
    local name="$1"
    case "$name" in
        *omega_cycle*.json) echo "witness" ;;
        *_review.md|*candidate_review.md) echo "review" ;;
        *_audit*.md|*_audit*.py) echo "audit" ;;
        SECURITY_AUDIT.md) echo "audit" ;;
        *_decision.md|hexa_lang_*_decision.md) echo "decision" ;;
        M*_definition*.md|*M3_*.md) echo "audit" ;;
        SESSION_*.md|NEXT_SESSION_*.md) echo "session" ;;
        README*.md|INDEX*.md|SYNTHESIS*.md|cross_repo_dashboard.md|R5_*.md|META_*.md) echo "corpus_doc" ;;
        falsifiers.jsonl) echo "registry" ;;
        falsifier_history*.jsonl) echo "ledger" ;;
        *.py|*.sh) echo "script" ;;
        *.json) echo "data" ;;
        *.md) echo "doc" ;;
        *) echo "other" ;;
    esac
}

extract_desc() {
    local f="$1"
    local desc=""
    case "$f" in
        *.md)
            # first H1/H2 heading after front-matter
            desc=$(awk '/^#+ / {sub(/^#+ +/,""); print; exit}' "$f" 2>/dev/null | cut -c1-80)
            ;;
        *.json)
            # 'title' OR 'cycle_id' field
            desc=$(python3 -c "
import json,sys
try:
    d=json.load(open('$f'))
    print(d.get('title', d.get('cycle_id', d.get('trawl_id', ''))))
except Exception: pass
" 2>/dev/null | cut -c1-80)
            ;;
        *.py|*.sh)
            # second line of file (usually description comment)
            desc=$(sed -n '2p' "$f" 2>/dev/null | sed 's/^[# ]*//' | cut -c1-80)
            ;;
        *.jsonl)
            desc="JSONL stream ($(wc -l <"$f" | tr -d ' ') lines)"
            ;;
    esac
    [ -z "$desc" ] && desc="(no description extracted)"
    echo "$desc"
}

# Generate
total=0
{
    echo "# design/hexa_sim/ INDEX (auto-generated)"
    echo ""
    echo "Generated by \`tool/hexa_sim_index_gen.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "For curated navigation see [README.md](README.md)."
    echo ""
    echo "| File | Type | Date | Bytes | Description |"
    echo "|------|------|------|-------|-------------|"
    for f in $(ls "$DIR" | grep -v '^INDEX.md$' | sort); do
        full="$DIR/$f"
        [ -f "$full" ] || continue
        type=$(classify "$f")
        # date heuristic: leading 2026-MM-DD or file mtime
        date=$(echo "$f" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1)
        [ -z "$date" ] && date=$(stat -f '%Sm' -t '%Y-%m-%d' "$full" 2>/dev/null || echo "-")
        bytes=$(stat -f '%z' "$full" 2>/dev/null || echo "?")
        desc=$(extract_desc "$full")
        # escape pipes in description
        desc=$(printf '%s' "$desc" | tr '|' '/')
        printf '| `%s` | %s | %s | %s | %s |\n' "$f" "$type" "$date" "$bytes" "$desc"
        total=$((total + 1))
    done
    echo ""
    echo "**Total**: $total files."
} > "$OUT"

# Sentinel + count summary
echo "__HEXA_SIM_INDEX_GEN__ PASS files=$total out=$OUT" >&2
exit 0
