/// Markdown document generator for NEXUS-6 discoveries.

/// Generate a structured markdown discovery report.
pub fn generate_markdown(
    title: &str,
    abstract_text: &str,
    findings: &[(String, f64)],
    n6_connections: &[String],
    predictions: &[String],
) -> String {
    let mut md = String::new();

    md.push_str(&format!("# {}\n\n", title));
    md.push_str(&format!("## Abstract\n\n{}\n\n", abstract_text));

    // Core theorem
    md.push_str("## Foundation\n\n");
    md.push_str("sigma(n) * phi(n) = n * tau(n)  <==>  n = 6\n\n");

    // Findings table
    if !findings.is_empty() {
        md.push_str("## Findings\n\n");
        md.push_str("| Metric | Value | n=6 Match | Grade |\n");
        md.push_str("|--------|-------|-----------|-------|\n");

        for (name, value) in findings {
            let (match_name, quality) = crate::verifier::n6_check::n6_match(*value);
            let grade = if quality >= 1.0 {
                "EXACT"
            } else if quality >= 0.8 {
                "CLOSE"
            } else if quality >= 0.5 {
                "WEAK"
            } else {
                "--"
            };
            md.push_str(&format!(
                "| {} | {:.4} | {} | {} |\n",
                name, value, match_name, grade
            ));
        }
        md.push('\n');
    }

    // n6 connections
    if !n6_connections.is_empty() {
        md.push_str("## n=6 Connections\n\n");
        for conn in n6_connections {
            md.push_str(&format!("- {}\n", conn));
        }
        md.push('\n');
    }

    // Predictions
    if !predictions.is_empty() {
        md.push_str("## Testable Predictions\n\n");
        for (i, pred) in predictions.iter().enumerate() {
            md.push_str(&format!("{}. {}\n", i + 1, pred));
        }
        md.push('\n');
    }

    md.push_str("---\n*Generated by NEXUS-6 Discovery Engine*\n");

    md
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_markdown() {
        let md = generate_markdown(
            "Test Report",
            "Abstract text",
            &[("sigma".to_string(), 12.0)],
            &["sigma=12 is EXACT".to_string()],
            &["Prediction A".to_string()],
        );
        assert!(md.contains("# Test Report"));
        assert!(md.contains("| sigma | 12.0000 | sigma | EXACT |"));
        assert!(md.contains("sigma=12 is EXACT"));
        assert!(md.contains("1. Prediction A"));
    }

    #[test]
    fn test_markdown_empty_sections() {
        let md = generate_markdown("Empty", "No data.", &[], &[], &[]);
        assert!(md.contains("# Empty"));
        assert!(!md.contains("## Findings"));
        assert!(!md.contains("## n=6 Connections"));
    }

    #[test]
    fn test_markdown_has_foundation() {
        let md = generate_markdown("T", "A", &[], &[], &[]);
        assert!(md.contains("sigma(n) * phi(n) = n * tau(n)"));
    }
}
